"""Initial migration with all models

Revision ID: f9c07f51ef7f
Revises: 
Create Date: 2025-11-30 02:22:41.895981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c07f51ef7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands_sustainability',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('brand_name_normalized', sa.String(length=100), nullable=True),
    sa.Column('transparency_index_score', sa.Integer(), nullable=True),
    sa.Column('transparency_year', sa.Integer(), nullable=True),
    sa.Column('publishes_supplier_list', sa.Boolean(), nullable=True),
    sa.Column('discloses_ghg_emissions', sa.Boolean(), nullable=True),
    sa.Column('discloses_water_usage', sa.Boolean(), nullable=True),
    sa.Column('discloses_waste_data', sa.Boolean(), nullable=True),
    sa.Column('has_living_wage_commitment', sa.Boolean(), nullable=True),
    sa.Column('has_climate_targets', sa.Boolean(), nullable=True),
    sa.Column('tier1_suppliers_disclosed', sa.Integer(), nullable=True),
    sa.Column('tier2_suppliers_disclosed', sa.Integer(), nullable=True),
    sa.Column('countries_manufacturing', sa.Integer(), nullable=True),
    sa.Column('planet_score', sa.Integer(), nullable=True),
    sa.Column('people_score', sa.Integer(), nullable=True),
    sa.Column('animal_score', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index('ix_brands_brand_name', 'brands_sustainability', ['brand_name'], unique=False)
    op.create_index('ix_brands_brand_name_normalized', 'brands_sustainability', ['brand_name_normalized'], unique=False)
    op.create_index(op.f('ix_brands_sustainability_brand_name'), 'brands_sustainability', ['brand_name'], unique=True)
    op.create_index(op.f('ix_brands_sustainability_brand_name_normalized'), 'brands_sustainability', ['brand_name_normalized'], unique=False)
    op.create_table('calculation_parameters',
    sa.Column('param_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('param_id'),
    sa.UniqueConstraint('parameter_name')
    )
    op.create_index('ix_parameter_name', 'calculation_parameters', ['parameter_name'], unique=False)
    op.create_table('clothing_types_reference',
    sa.Column('clothing_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clothing_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('typical_weight_grams', sa.Integer(), nullable=False),
    sa.Column('weight_range_min', sa.Integer(), nullable=True),
    sa.Column('weight_range_max', sa.Integer(), nullable=True),
    sa.Column('typical_wears', sa.Integer(), nullable=True),
    sa.Column('wash_frequency', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('clothing_type_id')
    )
    op.create_index('ix_clothing_type', 'clothing_types_reference', ['clothing_type'], unique=False)
    op.create_index(op.f('ix_clothing_types_reference_clothing_type'), 'clothing_types_reference', ['clothing_type'], unique=True)
    op.create_table('materials_reference',
    sa.Column('material_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.String(length=50), nullable=False),
    sa.Column('material_category', sa.String(length=30), nullable=True),
    sa.Column('co2_per_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('water_liters_per_kg', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('energy_mj_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_use_m2_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('spinning_multiplier', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('weaving_multiplier', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('dyeing_multiplier', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('finishing_multiplier', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('production_region', sa.String(length=50), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index('ix_material_name', 'materials_reference', ['material_name'], unique=False)
    op.create_index(op.f('ix_materials_reference_material_name'), 'materials_reference', ['material_name'], unique=True)
    op.create_table('platform_impact_statistics',
    sa.Column('platform_stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_period', sa.String(length=20), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('total_active_users', sa.Integer(), nullable=True),
    sa.Column('new_users_this_period', sa.Integer(), nullable=True),
    sa.Column('users_with_swaps', sa.Integer(), nullable=True),
    sa.Column('total_swaps_completed', sa.Integer(), nullable=True),
    sa.Column('total_clothing_swapped', sa.Integer(), nullable=True),
    sa.Column('swaps_this_period', sa.Integer(), nullable=True),
    sa.Column('total_co2_saved_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_co2_saved_tons', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_water_saved_liters', sa.Numeric(precision=18, scale=1), nullable=True),
    sa.Column('total_water_saved_million_liters', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_energy_saved_kwh', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_energy_saved_mwh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equivalent_km_not_driven', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('equivalent_cars_off_road', sa.Integer(), nullable=True),
    sa.Column('equivalent_trees_planted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equivalent_olympic_pools', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('top_categories_swapped', sa.JSON(), nullable=True),
    sa.Column('top_cities', sa.JSON(), nullable=True),
    sa.Column('top_countries', sa.JSON(), nullable=True),
    sa.Column('growth_rate_swaps', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('growth_rate_users', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('growth_rate_impact', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_co2_per_swap', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('avg_swaps_per_user', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_impact_per_user', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('platform_stat_id'),
    sa.UniqueConstraint('stat_period', 'period_start_date', name='uq_platform_impact_statistics_period_start')
    )
    op.create_index('ix_platform_impact_statistics_period_start_date', 'platform_impact_statistics', ['period_start_date'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('preferred_units', sa.String(length=10), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('total_swaps', sa.Integer(), nullable=True),
    sa.Column('impact_points', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('profile_public', sa.Boolean(), nullable=True),
    sa.Column('share_stats', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('clothing_items',
    sa.Column('clothing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('clothing_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('material_composition', sa.JSON(), nullable=False),
    sa.Column('composition_verified', sa.Boolean(), nullable=True),
    sa.Column('composition_verification_count', sa.Integer(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('weight_estimated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('times_swapped', sa.Integer(), nullable=True),
    sa.Column('primary_image_url', sa.String(length=255), nullable=True),
    sa.Column('additional_images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('material_composition IS NOT NULL', name='material_composition_not_null'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands_sustainability.brand_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('clothing_id')
    )
    op.create_index(op.f('ix_clothing_items_brand'), 'clothing_items', ['brand'], unique=False)
    op.create_index('ix_clothing_items_brand_id', 'clothing_items', ['brand_id'], unique=False)
    op.create_index(op.f('ix_clothing_items_clothing_type'), 'clothing_items', ['clothing_type'], unique=False)
    op.create_index('ix_clothing_items_owner_user_id', 'clothing_items', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_clothing_items_status'), 'clothing_items', ['status'], unique=False)
    op.create_table('user_impact_statistics',
    sa.Column('user_stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_swaps_completed', sa.Integer(), nullable=True),
    sa.Column('total_clothing_given', sa.Integer(), nullable=True),
    sa.Column('total_clothing_received', sa.Integer(), nullable=True),
    sa.Column('cumulative_co2_saved_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cumulative_water_saved_liters', sa.Numeric(precision=15, scale=1), nullable=True),
    sa.Column('cumulative_energy_saved_kwh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equivalent_km_not_driven', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equivalent_trees_planted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('equivalent_days_drinking_water', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('equivalent_smartphone_charges', sa.Integer(), nullable=True),
    sa.Column('top_category_swapped', sa.String(length=50), nullable=True),
    sa.Column('top_category_count', sa.Integer(), nullable=True),
    sa.Column('top_category_impact_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('monthly_impact_timeline', sa.JSON(), nullable=True),
    sa.Column('platform_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impact_rank', sa.Integer(), nullable=True),
    sa.Column('badges_earned', sa.JSON(), nullable=True),
    sa.Column('stats_period', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_stat_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_user_impact_statistics_user_id')
    )
    op.create_index('ix_user_impact_statistics_cumulative_co2_saved_kg', 'user_impact_statistics', ['cumulative_co2_saved_kg'], unique=False)
    op.create_index('ix_user_impact_statistics_impact_rank', 'user_impact_statistics', ['impact_rank'], unique=False)
    op.create_index('ix_user_impact_statistics_user_id', 'user_impact_statistics', ['user_id'], unique=False)
    op.create_table('clothing_environmental_impact',
    sa.Column('impact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('new_material_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_manufacturing_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_dyeing_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_transport_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_packaging_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_use_phase_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_end_of_life_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('new_total_co2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('new_material_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('new_processing_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('new_dyeing_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('new_total_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('new_total_energy_mj', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_total_energy_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reuse_collection_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reuse_sorting_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reuse_transport_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reuse_platform_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reuse_total_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('avoided_production_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('replacement_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('net_avoided_co2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('net_avoided_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('net_avoided_energy_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('impact_reduction_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculation_version', sa.String(length=10), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.Column('data_quality_score', sa.String(length=20), nullable=True),
    sa.Column('assumed_wears', sa.Integer(), nullable=True),
    sa.Column('assumed_washes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing_items.clothing_id'], ),
    sa.PrimaryKeyConstraint('impact_id'),
    sa.UniqueConstraint('clothing_id'),
    sa.UniqueConstraint('clothing_id', name='uq_clothing_environmental_impact_clothing_id')
    )
    op.create_index('ix_clothing_environmental_impact_clothing_id', 'clothing_environmental_impact', ['clothing_id'], unique=False)
    op.create_table('data_quality_tracking',
    sa.Column('quality_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('has_exact_weight', sa.Boolean(), nullable=True),
    sa.Column('has_verified_composition', sa.Boolean(), nullable=True),
    sa.Column('has_brand_data', sa.Boolean(), nullable=True),
    sa.Column('composition_source', sa.String(length=30), nullable=True),
    sa.Column('material_data_quality', sa.Integer(), nullable=True),
    sa.Column('calculation_confidence', sa.Integer(), nullable=True),
    sa.Column('co2_uncertainty_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('water_uncertainty_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_quality', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing_items.clothing_id'], ),
    sa.PrimaryKeyConstraint('quality_id')
    )
    op.create_index('ix_data_quality_tracking_clothing_id', 'data_quality_tracking', ['clothing_id'], unique=False)
    op.create_table('material_composition_contributions',
    sa.Column('contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('contributor_user_id', sa.Integer(), nullable=False),
    sa.Column('material_composition', sa.JSON(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('verified_by_others', sa.Integer(), nullable=True),
    sa.Column('flagged_incorrect', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing_items.clothing_id'], ),
    sa.ForeignKeyConstraint(['contributor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_index('ix_material_composition_contributions_clothing_contributor', 'material_composition_contributions', ['clothing_id', 'contributor_user_id'], unique=False)
    op.create_index('ix_material_composition_contributions_clothing_id', 'material_composition_contributions', ['clothing_id'], unique=False)
    op.create_index('ix_material_composition_contributions_contributor_user_id', 'material_composition_contributions', ['contributor_user_id'], unique=False)
    op.create_table('swaps',
    sa.Column('swap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('user1_clothing_id', sa.Integer(), nullable=False),
    sa.Column('user2_clothing_id', sa.Integer(), nullable=False),
    sa.Column('swap_type', sa.String(length=20), nullable=True),
    sa.Column('swap_location', sa.String(length=100), nullable=True),
    sa.Column('swap_event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('transport_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('transport_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user1_clothing_id != user2_clothing_id', name='different_clothing_items'),
    sa.CheckConstraint('user1_id != user2_id', name='different_users'),
    sa.ForeignKeyConstraint(['user1_clothing_id'], ['clothing_items.clothing_id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user2_clothing_id'], ['clothing_items.clothing_id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('swap_id')
    )
    op.create_index('ix_swaps_completed_date', 'swaps', ['completed_date'], unique=False)
    op.create_index('ix_swaps_status', 'swaps', ['status'], unique=False)
    op.create_index('ix_swaps_user1_clothing_id', 'swaps', ['user1_clothing_id'], unique=False)
    op.create_index('ix_swaps_user1_id', 'swaps', ['user1_id'], unique=False)
    op.create_index('ix_swaps_user1_user2', 'swaps', ['user1_id', 'user2_id'], unique=False)
    op.create_index('ix_swaps_user2_clothing_id', 'swaps', ['user2_clothing_id'], unique=False)
    op.create_index('ix_swaps_user2_id', 'swaps', ['user2_id'], unique=False)
    op.create_table('swap_environmental_impact',
    sa.Column('swap_impact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('swap_id', sa.Integer(), nullable=False),
    sa.Column('user1_clothing_avoided_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('user1_clothing_avoided_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('user1_clothing_avoided_energy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user2_clothing_avoided_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('user2_clothing_avoided_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('user2_clothing_avoided_energy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_swap_avoided_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_swap_avoided_water', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('total_swap_avoided_energy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('swap_transport_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('net_swap_impact_co2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['swap_id'], ['swaps.swap_id'], ),
    sa.PrimaryKeyConstraint('swap_impact_id'),
    sa.UniqueConstraint('swap_id'),
    sa.UniqueConstraint('swap_id', name='uq_swap_environmental_impact_swap_id')
    )
    op.create_index('ix_swap_environmental_impact_swap_id', 'swap_environmental_impact', ['swap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_swap_environmental_impact_swap_id', table_name='swap_environmental_impact')
    op.drop_table('swap_environmental_impact')
    op.drop_index('ix_swaps_user2_id', table_name='swaps')
    op.drop_index('ix_swaps_user2_clothing_id', table_name='swaps')
    op.drop_index('ix_swaps_user1_user2', table_name='swaps')
    op.drop_index('ix_swaps_user1_id', table_name='swaps')
    op.drop_index('ix_swaps_user1_clothing_id', table_name='swaps')
    op.drop_index('ix_swaps_status', table_name='swaps')
    op.drop_index('ix_swaps_completed_date', table_name='swaps')
    op.drop_table('swaps')
    op.drop_index('ix_material_composition_contributions_contributor_user_id', table_name='material_composition_contributions')
    op.drop_index('ix_material_composition_contributions_clothing_id', table_name='material_composition_contributions')
    op.drop_index('ix_material_composition_contributions_clothing_contributor', table_name='material_composition_contributions')
    op.drop_table('material_composition_contributions')
    op.drop_index('ix_data_quality_tracking_clothing_id', table_name='data_quality_tracking')
    op.drop_table('data_quality_tracking')
    op.drop_index('ix_clothing_environmental_impact_clothing_id', table_name='clothing_environmental_impact')
    op.drop_table('clothing_environmental_impact')
    op.drop_index('ix_user_impact_statistics_user_id', table_name='user_impact_statistics')
    op.drop_index('ix_user_impact_statistics_impact_rank', table_name='user_impact_statistics')
    op.drop_index('ix_user_impact_statistics_cumulative_co2_saved_kg', table_name='user_impact_statistics')
    op.drop_table('user_impact_statistics')
    op.drop_index(op.f('ix_clothing_items_status'), table_name='clothing_items')
    op.drop_index('ix_clothing_items_owner_user_id', table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_clothing_type'), table_name='clothing_items')
    op.drop_index('ix_clothing_items_brand_id', table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_brand'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_platform_impact_statistics_period_start_date', table_name='platform_impact_statistics')
    op.drop_table('platform_impact_statistics')
    op.drop_index(op.f('ix_materials_reference_material_name'), table_name='materials_reference')
    op.drop_index('ix_material_name', table_name='materials_reference')
    op.drop_table('materials_reference')
    op.drop_index(op.f('ix_clothing_types_reference_clothing_type'), table_name='clothing_types_reference')
    op.drop_index('ix_clothing_type', table_name='clothing_types_reference')
    op.drop_table('clothing_types_reference')
    op.drop_index('ix_parameter_name', table_name='calculation_parameters')
    op.drop_table('calculation_parameters')
    op.drop_index(op.f('ix_brands_sustainability_brand_name_normalized'), table_name='brands_sustainability')
    op.drop_index(op.f('ix_brands_sustainability_brand_name'), table_name='brands_sustainability')
    op.drop_index('ix_brands_brand_name_normalized', table_name='brands_sustainability')
    op.drop_index('ix_brands_brand_name', table_name='brands_sustainability')
    op.drop_table('brands_sustainability')
    # ### end Alembic commands ###